mozilla/send

- app.js
- package-lock.json
- package.json
- public/download.js
- public/upload.js
use `npm run format`
next step might be to autorun it as a git hook
> added prettier for js formatting

- package.json
> Tweak the package.json file

- frontend/src/download.js
- frontend/src/fileSender.js
- frontend/src/upload.js
- frontend/src/utils.js
> added notifications

- frontend/src/download.js
- frontend/src/upload.js
- package-lock.json
- public/main.css
- server/portal_server.js
- server/storage.js
- views/download.handlebars
- views/index.handlebars
-Added download and upload progress bars
-Re-enabled copy link button after 3s
Closes #51 and #84
> Progress bars

- server/portal_server.js
@dannycoates This is needed to comply with [Dockerflow](https://github.com/mozilla-services/Dockerflow).
> add /__lbheartbeat__ endpoint

- circle.yml
pushing to `mozilla/fileshare` will automatically deploy `latest` to dev and tags to stage
> change docker image name and add builds for tags

- circle.yml
> added docker service to circle.yml

- circle.yml
> fix docker build

- README.md
- docs/docker.md
> Update README with some more details

- frontend/src/upload.js
- views/index.handlebars
> Hide table header on empty list

- public/main.css
> Add word wraps to table

- circle.yml
> build docker image with new name

- frontend/src/download.js
- frontend/src/fileReceiver.js
- frontend/src/fileSender.js
- frontend/src/upload.js
- frontend/src/utils.js
- server/server.js
- server/storage.js
- views/download.handlebars
- views/index.handlebars
Based on the ones from testpilot.firefox.com
@dnarcese I had to remove the inline event handlers. We'll need to do the same for the new design.
ugh. there's a rogue reformat commit in here. just pay attention to the csp commit.
> Add CSP directives

- public/main.css
- views/index.handlebars
> change size of send another file links

- views/index.handlebars
- views/layouts/main.handlebars
> change learn more and github links

- public/main.css
- views/download.handlebars
- views/index.handlebars
- views/layouts/main.handlebars
> move head and html tags to main template

- frontend/src/fileSender.js
- frontend/src/upload.js
- server/server.js
- server/storage.js
> added functionality to cancel uploads

- frontend/src/download.js
- frontend/src/upload.js
- views/download.handlebars
we can do #225 without a new function
> escape filename in the ui

- frontend/src/download.js
- frontend/src/upload.js
- views/download.handlebars
- views/index.handlebars
> allow send another file link to open in new tab

- docs/faq.md
@pdehaan I wasn't sure what your ref comments were in the doc.  What should I add?
> add FAQ. Fixes #186

- public/main.css
> change how the file upload box expands

- public/main.css
Fixes #233 
Fixes #244 (I'm pretty sure...)
> make footer not overlap

- frontend/src/upload.js
> only allow drag and drop on upload page

- frontend/src/upload.js
> better sync percent with progress bar

- frontend/src/download.js
> sync download progress bar with percentage

- README.md
Also changes the style of the CircleCI badge to match.
> Adds 'Available on Test Pilot' badge.

- .eslintignore
- .gitignore
- circle.yml
- frontend/src/common.js
- frontend/src/download.js
- frontend/src/upload.js
- package-lock.json
- package.json
- server/server.js
- views/download.handlebars
- views/index.handlebars
- views/layouts/main.handlebars
- views/notfound.handlebars
fixes #209 
unfortunately we can't easily use watchify for `npm run dev` but we can fix that if it becomes a problem
> create separate js bundles for upload/download pages

- frontend/src/download.js
- frontend/src/upload.js
- server/server.js
- views/index.handlebars
- views/unsupported.handlebars
> created /unsupported page and added gcmCompliant to /download page

- frontend/src/upload.js
- public/locales/send.en-US.ftl
> dealing with invalid drag and drops

- docker-compose.yml
- docs/docker.md
- server/config.js
@relud I renamed the environment variables. cool? These will need to change in the deployment
> renamed environment variables to remove P2P_ prefix

- frontend/src/upload.js
- package-lock.json
- public/locales/send.en-US.ftl
- public/main.css
Fixes #237 
The popup still causes a horizontal scroll on smaller screens...not sure how to fix that
> restyle delete popup

- frontend/src/fileReceiver.js
- frontend/src/upload.js
- public/main.css
- server/server.js
- server/storage.js
addresses the null problem in #309
> expired ids should reject instead of returning null

- public/main.css
> fix German footer

- public/main.css
> fix feedback button jump

- frontend/src/upload.js
- frontend/src/utils.js
> fix functionality on firefox 50 and 51

- public/main.css
> center percentage text on all browser versions

- public/main.css
> don't wrap file list headers

- public/main.css
Fixes #216 
Fixes #308 
Also addresses an alignment issue with the download progress percentage
> wrap long file names

- docs/CODEOWNERS
> Add docs/CODEOWNERS file

- frontend/src/storage.js
> Make order of uploaded files in list consistent

- frontend/src/storage.js
- frontend/src/utils.js
> catch JSON.parse errors of storage metadata

- frontend/src/fileReceiver.js
fixes #151 
This could use better messaging but at least with this the server won't delete the file before you can try the correct key. We should follow up with a messaging issue.
> throw key errors before download begins

- views/layouts/main.handlebars
> Add X-UA-Compatible meta tag

- views/layouts/main.handlebars
- views/unsupported.handlebars
This adds rel noopener noreferrer values to target='_blank' anchor elements. See #439
> Add rel noopener noreferrer to target='_blank' anchor elements (Fixes #439)

- frontend/src/common.js
- frontend/src/download.js
- frontend/src/metrics.js
- frontend/src/upload.js
- server/server.js
- views/download.handlebars
- views/index.handlebars
- views/notfound.handlebars
consolidated the metrics code into metrics.js
> refactored metrics

- frontend/src/upload.js
- views/index.handlebars
> attach delete-file handler only after upload

- package-lock.json
- test/frontend/driver.js
- test/frontend/frontend.test.js
- test/server/server.test.js
> removed references to checksums in frontend tests

- views/layouts/main.handlebars
Solves #438 and together solves #440.
> Fixing bug #438 by adding role attribute to anchor tags and alt attribute images

- frontend/src/download.js
- frontend/src/fileReceiver.js
- server/server.js
- test/server/server.test.js
- webpack.config.js
> set the mime type in the download blob

- frontend/src/metrics.js
> added missing exit event cases

- package.json
> fixed build:css on windows

- frontend/src/.eslintrc.yml
- frontend/src/common.js
- frontend/src/download.js
- frontend/src/fileReceiver.js
- frontend/src/fileSender.js
- frontend/src/links.js
- frontend/src/metrics.js
- frontend/src/progress.js
- frontend/src/storage.js
- frontend/src/upload.js
- frontend/src/utils.js
- package-lock.json
- package.json
- server/server.js
- webpack.config.js
> use import/export in the frontend code

- frontend/src/main.css
> fix japanese browse button

- README.md
**in this PR I did basically:**
- *add separators to README file*
---
**I did this because:**
- *i feel it improves the overall flow of the file*
> adding separators to README

- app/experiments.js
- app/main.js
- app/metrics.js
- app/storage.js
- app/templates/welcome.js
- assets/main.css
- package-lock.json
- package.json
- server/state.js
> added first A/B experiment

- app/templates/uploadPassword.js
please see my comment https://github.com/mozilla/send/issues/623#issuecomment-341301803 for a description.
Does not result in the expected action, but allows the password form to work correctly if Firefox restarts while it is open
> Partial fix for #623

- app/utils.js
this addresses part of #586 -- the problem of q values throwing an uncaught exception and preventing files from uploading or downloading.
> wrap number localization in try/catch

- assets/main.css
This should fix #609 
Preview of changes
> adjusted line height of label : fixes #609

- README.md
[Docs] - README.md - minor spelling fixes
> [Docs] - README.md - minor spelling fixes

- assets/main.css
fixes; #635 
@SoftVision-CosminMuntean , is this what you wanted ?
@dannycoates thanks for the help. Actually I was trying to hover the check sign inside the checkbox that is why I was stuck over the issue of mouse event listeners
changes are as follows
> checkbox now has a hover effect: fixes #635

- app/templates/share.js
- assets/main.css
fixes : #217 
@dannycoates , I'm very sorry as I'm troubling you again. As mentioned by @SoftVision-CiprianMuresan , pull request #684  didn't fix the issue in **firefox** . So I have made the corrections. The error was caused due to instertion of `div` inside `button`. Now I have fixed that too. Well do you also want me to modify the css for the popup for mobile view too in this PR.
The below GIF can be seen
Mobile View Of Popup
> Popup for delete button attached

- app/experiments.js
- app/templates/fxPromo.js
- assets/main.css
> Gradient experiment

- public/locales/en-US/send.ftl
The only change is for the comments sigil. 
CC @pike
> Switch en-US FTL file to new syntax

- app/fileReceiver.js
- app/fileSender.js
- app/pages/download/index.js
- app/pages/upload/index.js
- app/templates/progress/index.js
- app/templates/progress/progress.css
> added indefinite progress mode

- app/base.css
- app/fileManager.js
- app/ownedFile.js
- app/pages/welcome/index.js
- app/templates/downloadPassword/downloadPassword.css
- app/templates/passwordInput/index.js
- app/templates/passwordInput/passwordInput.css
- app/templates/setPasswordSection/index.js
- public/locales/en-US/send.ftl
> added maxPasswordLength and passwordError messages

- package-lock.json
- package.json
- server/routes/index.js
- webpack.config.js
> removed unsafe-inline styles via svgo-loader

- app/templates/progress/index.js
- app/templates/progress/progress.css
> use a separate circle in the progress svg for indefinite progress

- app/templates/selectbox/selectbox.css
Issue fixes related to https://github.com/mozilla/send/issues/820.
> changes related to arrow positioning

- app/api.js
- package-lock.json
- package.json
- server/limiter.js
- server/routes/index.js
- server/routes/upload.js
- server/storage/fs.js
- server/storage/s3.js
- test/backend/s3-tests.js
We never ended up using multipart uploads and it'll be much easier to support streaming without it.
> refactored upload away from multipart forms to binary data

- app/main.js
- app/pasteManager.js
> Fix #843: Upload image on paste

- app/api.js
- server/routes/download.js
- test/frontend/tests/workflow-tests.js
> fixes #844

- app/api.js
- app/capabilities.js
- app/fileManager.js
- app/fileReceiver.js
- app/main.js
- app/serviceWorker.js
- app/utils.js
- package-lock.json
- package.json
- server/routes/index.js
- test/frontend/tests/workflow-tests.js
- webpack.config.js
This adds the old blob download method back for some backward compatibility.
> began adding capability flags

- app/base.css
- app/pages/welcome/welcome.css
- app/templates/title/title.css
Made some changes for #949 
**1. Title ->**
original:
updated:
**2. Button ->**
original:
updated:
> UI Review German Edition

- app/ui/account.js
> Changed sign in area

- app/ui/archiveTile.js
- public/locales/en-US/send.ftl
> added total size to wip tile

- server/layout.js
- server/routes/index.js
- server/routes/webmanifest.js
https://developer.mozilla.org/en-US/docs/Web/Manifest
> added a webmanifest

- Dockerfile
- circle.yml
- package-lock.json
- package.json
- test/frontend/runner.js
> Upgrade to Node v10

- app/ui/header.js
- app/utils.js
> don't make title a link on android

- app/ui/expiryOptions.js
- app/ui/selectbox.js
- test/integration/download-tests.js
- test/integration/pages/desktop/home_page.js
Added a test for `2 downloads` being changed to `1 download` on the home page.
> [Integration-Test] Add test for number of downloads, fixes #810

- app/main.css
- app/ui/archiveTile.js
- app/ui/copyDialog.js
- app/ui/expiryOptions.js
- app/ui/header.js
- app/ui/okDialog.js
- app/ui/signupDialog.js
also sorted main.css alphabetically
> refactored styles to extract btn

- app/ui/archiveTile.js
- app/ui/header.js
- app/utils.js
still needs the icon
fixes #1081
> added download link to tile

- app/ui/archiveTile.js
- app/ui/download.js
- public/locales/en-US/send.ftl
> full page download ui

- android/app/src/main/java/org/mozilla/sendandroid/MainActivity.kt
> android: exclude self from share intent

- android/app/build.gradle
- android/app/src/main/java/org/mozilla/sendandroid/MainActivity.kt
- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
To do so, we clear the webview history once the login process is complete so that the intermediate redirect urls used by the login process are not in the history.
Also, update the versions of some of the libraries we use.
> Fix #1145 Fix the back button after logging in.

- server/routes/download.js
Related to Issue https://github.com/mozilla/send/issues/1149
See PR https://github.com/mozilla/send/pull/1182
> 1149-vnext-fix-aborted-event-gt-node-v9.x.x

- app/main.js
- app/utils.js
- public/locales/en-US/send.ftl
v3.0.0 has been tagged. This will be for the next release.
fixes #1211
> localize file sizes

- docs/encryption.md
(That's all! Thank you for *Send*!)
> Fix a small typo in docs/encryption.md: it's --> its

- test/integration/download-tests.js
> [Integration-Test] Add test to ensure that file size stays consistent

- README.md
Before:
----
After:
----
--Suriyaa
> Replace title with Firefox Send logo

- app/capabilities.js
- app/controller.js
- app/main.js
- app/metrics.js
- app/ui/copyDialog.js
- app/ui/modal.js
- app/ui/shareDialog.js
- app/ui/surveyDialog.js
- app/user.js
- app/utils.js
- public/locales/en-US/send.ftl
- server/config.js
- server/initScript.js
- server/state.js
Enabled by setting a `SURVEY_URL` env variable.
> added survey dialog

- app/ui/promo.js
- tailwind.js
> tweak promo banner to match spec'

- app/main.css
> Fixes blurry Sign in button when hovered

- README.md
- package.json
I ran into some setup snafus and turns out it's b/c we're expecting node 10.x. Updating package.json and README accordingly.
> task: update engines in package.json and README to clarify that node 10x is expected.

- app/ui/downloadPassword.js
- package-lock.json
- test/integration/download-tests.js
- test/integration/pages/desktop/download_page.js
- test/integration/pages/desktop/home_page.js
This PR strips all URL parameters between file id and secret key before password validation.
Connected issue https://github.com/mozilla/send/issues/1354
> Strip tracking URL params

- app/readme.md
Hey,
reading the documentation I came across a link to the routes file which has changed its location so I updated the link.
> Fixes link to routes file

- package.json
All three are at 100%, quickly tested them on the DEV server.
> Add new locales (an, gn, mix)

- app/main.js
- app/ui/body.js
- app/ui/promo.js
Hey @dannycoates I didn't use l10n here because the VPN is US only at the moment. This seemed easy. LMK if you want me to make any changes.
> update promo to be for the vpn

- server/config.js
- server/storage/redis.js
Allow to customize Redis retry strategy params from config
> Allow to set custom retry parameters

- app/ui/promo.js
The full-device VPN is now at https://vpn.mozilla.org.
> Update URL for the VPN

- README.md
Added a few commas, deleted an extra period.
Thank you so much for making Firefox Send! It's very useful for sending sensitive files to others.
Keep up the good work!
> Fixed a few minor formatting issues

- server/config.js
- server/storage/s3.js
- test/backend/s3-tests.js
See https://github.com/mozilla/send/issues/1239
> Choose your endpoint.
