- frontend/src/fileSender.js
- frontend/src/upload.js
- public/main.css
- server/portal_server.js
- views/download.handlebars
- views/index.handlebars
Added drag & drop as well as a delete file confirmation.
Closes #61
> Drag & drop

- .eslintignore
- .eslintrc.yml
- package-lock.json
- package.json
This only adds ESLint, not CSS/style linting.
Ref: #27
> Adding basic ESLint config

- .eslintignore
- .eslintrc.yml
- .htmllintrc
- .stylelintrc
- frontend/src/download.js
- frontend/src/fileReceiver.js
- frontend/src/fileSender.js
- frontend/src/upload.js
- frontend/src/utils.js
- package-lock.json
- package.json
- public/main.css
- server/config.js
- server/log.js
- server/portal_server.js
- server/storage.js
- views/download.handlebars
- views/index.handlebars
> Fix the linter errors

- package-lock.json
- package.json
> Optimize/minimize bundle.js for production

- package-lock.json
- package.json
Currently you get errors if you only install the dependencies and then run `npm start`:
```sh
$ NODE_ENV=production npm install
added 174 packages in 6.285s
$ npm start
> portal-alpha@1.0.0 prestart /Users/pdehaan/dev/github/mozilla/something-awesome
> npm run bundle
> portal-alpha@1.0.0 bundle /Users/pdehaan/dev/github/mozilla/something-awesome
> browserify frontend/src/main.js | uglifyjs > public/bundle.js
> portal-alpha@1.0.0 start /Users/pdehaan/dev/github/mozilla/something-awesome
> cross-env NODE_ENV=production node server/portal_server
sh: cross-env: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! portal-alpha@1.0.0 start: `cross-env NODE_ENV=production node server/portal_server`
npm ERR! spawn ENOENT
npm ERR!
npm …
```
> Move cross-env to a dep

- frontend/src/download.js
- frontend/src/fileReceiver.js
- frontend/src/fileSender.js
- frontend/src/upload.js
- package-lock.json
- server/config.js
- server/portal_server.js
- test/local.storage.test.js
- views/index.handlebars
-shows previous uploads on refresh
-fix Nevermind button
Fixes #58 
Fixes #125
> Load previous uploads

- package.json
- server/config.js
- server/log.js
- server/portal_server.js
- server/storage.js
- test/aws.storage.test.js
- test/local.storage.test.js
- views/download.handlebars
- views/index.handlebars
the `notLocalHost` field is problematic because it causes unexpected behavior when a new parameter is added to it but the environment hasn't caught up with the new variable. As example, adding the sentry_dsn, instead of simply not using sentry it forces the storage module to use the local file system instead of s3 if that env isn't set. It's better to have each variable control only the aspect of the code it's responsible for.
cc @abhinadduri
> remove notLocalHost

- frontend/src/upload.js
- server/log.js
File gets removed from list and localStorage when it is downloaded or expires
Fixes #144 and #58
> Remove expired uploads

- public/contribute.json
> WIP: Add basic contribute.json

- frontend/src/fileSender.js
- frontend/src/upload.js
- views/index.handlebars
When a file cannot be uploaded, show a very simple error page (which will be changed with new designs).
> Show error page if upload fails

- frontend/src/fileReceiver.js
- server/portal_server.js
- views/download.handlebars
> fixed issues in branch title

- README.md
- docs/metrics.md
Here's a first pass on metrics documentation based on the first pass at UX (#169) and [metrics acceptance criteria](https://docs.google.com/document/d/1VqaQ2nVxdHTvw0WADtgNtZxcYNnWGjPweVomGhF8Aqg/edit?ts=5925d95c#). It's important to read this in context of the [Test Pilot Experiment Metrics](https://github.com/mozilla/testpilot/blob/master/docs/experiments/ga.md) document, which prescribes standard uses that are not duplicated here.
[Read with Markdown parsed](https://github.com/chuckharmston/send/blob/5-metrics-docs/docs/metrics.md)
A lot of what is prescribed here is likely not practical or possible; I'll be very happy to discuss easier or alternate possibilities based on reality.
Thanks to @dannycoates and @johngruen for entertaining dozens of questions while I was getting oriented!
> Adds metrics documentation (closes #5).

- circle.yml
Completes one more checkbox on the security checklist.
Note that this runs on Circle-CI only, and not on any local scripts or local dependency or commit hooks.
> Add nsp check to circle ci

- frontend/src/download.js
- frontend/src/upload.js
- package-lock.json
- public/locales/send.en-US.ftl
- public/main.css
- views/download.handlebars
- views/index.handlebars
> add file size limit message

- frontend/src/upload.js
- public/locales/send.en-US.ftl
> add alert when uploading multiple files

- docs/metrics.md
This fixes a mistake in the metrics documentation: a duplicate metric. This merges `cd6` and `cd4` as `cd4`, then moves `cd7` to `cd6`.
CC @abhinadduri
> Remove duplicate custom metric.

- frontend/src/download.js
- frontend/src/fileSender.js
- frontend/src/upload.js
- package-lock.json
- public/locales/send.en-US.ftl
- server/config.js
- server/server.js
- server/storage.js
- test/unit/aws.storage.test.js
- test/unit/local.storage.test.js
- views/jsconfig.handlebars
Fixes #180
* adds an alert error to the ui if the selected file's size is too big
* aborts uploads on the server that are too big
* adds the `bytes` module cuz im lazy
> abort uploads over maxfilesize

- .eslintignore
- package.json
- test/.eslintrc.yml
The /public/ directory is an odd mix of generated and static files. We don't need to ESLint anything in there, and it was blowing up my computer because of minified l20n files that were being copied from node_modules, and an old bundle file.
> Stop ESLint from linting the /public/ directory

- frontend/src/download.js
Fixes #205 
Took the cheap way out and just copied the color. We could optionally copy the entire circle progress bar config and export it in ./utils.js so all the settings could be shared between upload and download (so we don't have to worry about the animation duration and sizes getting out of sync, etc).
> Update download progress bar color

- frontend/src/upload.js
This was mostly fixed in a previous PR that didn't allow drag and drop on any page other than the first. This to fix the edge case reproduced by:
- click the upload button, 
- drag and drop a file instead
- then click and select a second file and click upload
Fixes #160.
> fix: Don`t allow upload when not on the upload page.

- scripts/version.js
This ought to fix inconsistency between the tag version and version.json version for tagged builds
@pdehaan @relud r?
fixes #298
> use CIRCLE_TAG as version.json version if present

- frontend/src/upload.js
- package-lock.json
> don't show error page on upload cancel

- public/locales/send.en-US.ftl
- server/server.js
- views/layouts/main.handlebars
- views/legal.handlebars
> added legal page

- package.json
- server/config.js
- server/server.js
- views/layouts/main.handlebars
fixes #312 
@relud can we set `L10N_DEV=true` for send.dev.mozaws.net only?
> added L10N_DEV environment variable for making all languages available

- frontend/src/upload.js
- frontend/src/utils.js
the 
`  prefer-const: error` 
rule in eslint forces `const` in for loops, But firefox 50 and 51 break when this is enforced. Since Test pilot supports v50+ I think we should remove this from our code and lint rules. 
(I could not find a eslint rule related to this that would allow `let` in loops, so have removed it altogether)
re: #334
> support v 50 and 51 by not allowing const in loops

- public/locales/cs/send.ftl
- public/locales/cy/send.ftl
- public/locales/de/send.ftl
- public/locales/dsb/send.ftl
- public/locales/el/send.ftl
- public/locales/es-AR/send.ftl
- public/locales/es-ES/send.ftl
- public/locales/fr/send.ftl
- public/locales/fy-NL/send.ftl
- public/locales/hsb/send.ftl
- public/locales/hu/send.ftl
- public/locales/it/send.ftl
- public/locales/ja/send.ftl
- public/locales/kab/send.ftl
- public/locales/ms/send.ftl
- public/locales/nb-NO/send.ftl
- public/locales/pt-BR/send.ftl
- public/locales/pt-PT/send.ftl
- public/locales/sk/send.ftl
- public/locales/sl/send.ftl
- public/locales/sv-SE/send.ftl
- public/locales/zh-CN/send.ftl
- public/locales/zh-TW/send.ftl
Removing trailing spaces is irrelevant in this context (they should have one)
> Remove duplicate entities in localized FTL files

- frontend/src/upload.js
- public/main.css
Fixes #326 
Also, expand feedback button by default in mobile view since there's no hover state.
> Modify popup delete dialog

- frontend/src/common.js
- frontend/src/download.js
- frontend/src/upload.js
- public/locales/en-US/send.ftl
- public/main.css
- server/server.js
- views/unsupported.handlebars
@abhinadduri can you create an appropriate GA event for this?
Everyone else, any opinions on what should be shown on this page?
/unsupported/outdated now looks like this:
very similar to /unsupported/gcm 
link goes to "https://support.mozilla.org/kb/update-firefox-latest-version" which offers advice on how to update firefox
Fixes: #319.
Ref: #127.
> Show error page on firefox v49 and below

- public/locales/nn-NO/send.ftl
- public/locales/tr/send.ftl
Noticed this while playing w/ ```compare-locales l10n.toml . `ls public/locales` --data=json```
> Fix some missing .title attributes in dev-only locales

- frontend/src/download.js
- frontend/src/fileSender.js
- frontend/src/upload.js
- server/server.js
> Get rid of console.log statements

- views/jsconfig.handlebars
- views/unsupported.handlebars
> redirect ie to /unsupported

- public/main.css
The previous commit was to fix an IE issue, but it caused the footer to float over content on Chrome.
This worked for me, but maybe there's a better way?
> revert the IE fix to fix footer on chrome

- README.md
Words are not great. Suggestions/commits welcome!
r? @flodolo
> Add Pontoon URL to README

- public/main.css
I adjusted highlight targets to `h1` and `a`. Now it looks like this:
Not quite sure if this fits the original design.
> Adjust hover behavior on send-logo (#382)

- .gitignore
- package-lock.json
- package.json
- views/layouts/main.handlebars
fixes #395
and before @pdehaan mentions webpack, i know, but not right now
> add babel-polyfill

- .eslintrc.yml
`alert()` is a bit gross. So adding ESLint rule that warns on usage so we can eventually be shamed into a better UI solution (since `alert()` and `prompt()` and `confirm()` can eventually be dismissed by the user with a "stop doing this" option -- which would be some bad UX).
```sh
$ git grep "alert" frontend/src
frontend/src/upload.js:          alert(str);
frontend/src/upload.js:        .then(alert);
```
> Add ESLint no-alert shame rule

- circle.yml
- frontend/src/common.js
- package.json
- server/server.js
- views/jsconfig.handlebars
> filter the hash from error reports

- docs/faq.md
- frontend/src/upload.js
- views/index.handlebars
- views/layouts/main.handlebars
You can test this locally by toggling the `javascript.enabled` Boolean in _about:config_.
With a locale set of "fr", this totally looks like:
Fixes #373
> Add noscript tag

- server/server.js
Changed all promises into async functions for express.
I have attempted to promsify all Redis client methods as #64 described. It failed but I have no idea why, and I cannot log directly in [storage.js](https://github.com/mozilla/send/blob/424eb2c37ad50ab7778985edbea029e8683e4720/server/storage.js). Any help?
> Use async function instead of promise (#325)

- server/server.js
- views/layouts/main.handlebars
> Only include Fira CSS on /unsupported/* route

- public/locales/en-US/send.ftl
- views/unsupported.handlebars
Just adds a link to the relevant FAQ bits, although we still incur an l10n hit since I had to add a string.
Totally looks like:
Fixes #377
> Add link to FAQ in unsupported view

- public/main.css
Percentage number doesn't fit in the middle when using mobile browser, chrome, firefox and safari on desktop, this commit is simple solution.
**Before**
**After**
> fix percentage view on mobile layout

- frontend/src/download.js
- frontend/src/upload.js
- views/layouts/main.handlebars
> _blank all footer links

- frontend/src/upload.js
- public/main.css
Should handle disabled copy to clipboard.
But I have to find a way for something better than that : 
Fixes #108
> Handle copy clipboard disabled

- CONTRIBUTORS
- package.json
And a big thanks to all those wonderful contributors: 👏 
Fixes #397
> Add contributors script

- frontend/src/download.js
This seems to work locally for me, but it happens so quickly sometimes I have a hard time clicking fast enough.
Fixes #429
> Prevent download button from being clicked multiple times

- frontend/src/download.js
- frontend/src/upload.js
This PR add some improvements about perfs and good practices.
- Remove events shortcuts ( `.click` transformed to `.on('click')`
- Chain jQuery calls
- Store selectors to avoid DOM access when we had already find the DOM elements
- Change `$(document).ready` to `$(function () { })` with jQuery 3 it's recommended to use this form to listen the DOM ready events (see : https://api.jquery.com/ready/)
Fix : https://github.com/mozilla/send/issues/284
> Chain jQuery calls, do not use events alias and store selectors

- package.json
- public/locales/es-CL/send.ftl
- public/locales/tr/send.ftl
Fixing a few errors/warnings via ```compare-locales l10n.toml . `ls public/locales` ```.
This brings those locales up to 100%. Also added "el" and "uk" locales to `availableLanguages` array since they seem to be at 100% as well.
> Add a few missing strings from es-CL and tr locales

- frontend/src/download.js
- frontend/src/fileReceiver.js
- frontend/src/fileSender.js
- frontend/src/progress.js
- frontend/src/upload.js
- frontend/src/utils.js
- package-lock.json
- package.json
- public/locales/en-US/send.ftl
- server/server.js
- views/download.handlebars
- views/index.handlebars
Fixes #349 
Fixes #366
Fixes #462
> factored out progress into progress.js

- public/main.css
- views/index.handlebars
This update adds the requested CSS, thereby fixing the error message. See #436.
> Migrate width attribute to CSS (Fixes #436)

- frontend/src/links.js
- frontend/src/metrics.js
- package-lock.json
- package.json
- webpack.config.js
This is just a start at webpack and transpiling to es2015. 
@pdehaan I excluded the "env" preset for now for simplicity. We should revisit it along with removing the full polyfill.min.js script from the template in a follow up issue.
Bonus: fixes Edge (I think)
> added webpack

- package.json
This version has a useful protection against http header splitting
fixes #467
> Increase mimimum node version to 8.2.0

- frontend/src/download.js
- frontend/src/fileReceiver.js
- frontend/src/fileSender.js
- frontend/src/upload.js
- server/server.js
This removes the sha256 hash of the unencrypted file from the data sent to the server.
Our future product requirements may require us to send other identifying data at some point. Upon such a change we'll update the site to describe the change.
Note: The file name is still sent unencrypted. Work on that is being tracked in #69
> removed the file sha256 hash

- CONTRIBUTORS
- package.json
Adding latest contributors and changing sort order from number-of-commits to contributor name, to prevent needless. Should hopefully make diffs a bit easier to eyeball.
> Sort contributors alphabetically to prevent churn

- frontend/src/main.css
- views/download.handlebars
- views/index.handlebars
> Increase font weight to 500 on <button>s and <label>s

- frontend/src/progress.js
- frontend/src/utils.js
#479 piqued my interest as a fun little exercise.
This sets the tab title to the percent complete during an upload/download, but only if the page is not in focus.
Fixes #479
> added progress to tab title when not in focus

- frontend/src/download.js
- frontend/src/metrics.js
- frontend/src/storage.js
- frontend/src/upload.js
In Firefox when cookies are disabled so is localStorage. The current version 1.1.0 is completely unusable when this is set and I've noticed a few related errors on sentry. 
This PR makes uploading and downloading work, but the file list (as expected) does not.
> make the site mostly work when cookies (localStorage) are disabled

- package-lock.json
- package.json
- server/server.js
- webpack.config.js
Now `npm start` or `npm run dev` will rebuild js bundles when the source changes on localhost.
> added webpack-dev-middleware

- package-lock.json
- package.json
- server/server.js
> added precommit hook for format

- frontend/src/download.js
- frontend/src/fileList.js
- frontend/src/main.css
- frontend/src/progress.js
- frontend/src/upload.js
- package-lock.json
- package.json
- views/download.handlebars
- views/index.handlebars
This trims about 22kB from the bundles
> use svg for progress

- README.md
NodeJS version was increased to 8.2 due to possible http header splitting vulnerability
See: [https://github.com/mozilla/send/pull/469](https://github.com/mozilla/send/pull/469)
> Fixed minimum NodeJS version in README

- app/templates/welcome.js
- assets/main.css
> Make upload button focusable (accessibility/tab navigation)

- app/fileManager.js
> Hide cancel button when upload reaches 100%

- README.md
**this PR does basically aim at:**
- *introducing ToC to README.md file*
---
**main motivation behind such:**
- *improving accessaibility of the file*
- *turning the file easier to be read*
---
**by doing so, i firmly believe that:**
- *I may be contributing into a smaller extent to raise the interesting of users in returning to this repository by making the file easier to be read*
> introducing ToC to README.md

- app/fileManager.js
- app/fileReceiver.js
- app/fileSender.js
- app/metrics.js
- app/routes/download.js
- app/routes/home.js
- app/storage.js
- app/templates/downloadPassword.js
- app/templates/preview.js
- app/templates/share.js
- app/templates/uploadPassword.js
- app/templates/welcome.js
- app/utils.js
- assets/main.css
- docs/metrics.md
- package.json
- public/locales/en-US/send.ftl
- server/routes/index.js
- server/routes/metadata.js
- server/routes/pages.js
- server/routes/password.js
- server/routes/upload.js
- server/storage.js
- test/frontend/frontend.bundle.js
- test/frontend/frontend.test.js
- test/unit/local.storage.test.js
- webpack.config.js
This adds an optional password to the download url of the shared file. Also, file metadata is now encrypted, so the server will no longer know the filename or type of all new files, not just password protected ones.
After a password is set the server requires verification of the password before returning both the encrypted file metadata and encrypted file.
Known issues:
- Does not work on Safari < 11, yet
- A few remaining css style issues
- With multiple browsers attempting to download a password protected file its possible for the valid password to be rejected if the server's nonce has changed. Re-entering the password with the new nonce will work as expected. I don't expect this to be common in real life.
Closes #381 
Closes #69
> Add optional password to the download url

- assets/main.css
the result of this css change: 
Fixes: #594.
> align the "Password" and "Copy to clipboard" fields.

- app/templates/share.js
- app/templates/uploadPassword.js
- assets/main.css
select require password, the link and "copy" button get half opacity, and the button is disabled. When the checkbox is deselected or password is submitted the opacity is restored, and button is enabled.
result: 
Fixes: #606.
Fixes: #600.
Related: #587.
> disable copying link when password not completed

- app/fileManager.js
the `state.transfer` needs to be reset after the download as well, otherwise the check
`if (state.route === '/' && !state.transfer) {` in dragManager will fail.
Fixes: #584.
> allow drag and drop if navigating from shared page

- app/fileSender.js
fixes #620 
Summary: file.type can be empty (such as when the filename has no extension) , provide a default value to use should this happen when collecting the file metadata
> set a default MIME type in file metadata

- app/templates/downloadPassword.js
- app/templates/share.js
- app/templates/uploadPassword.js
- assets/main.css
- package-lock.json
- public/locales/en-US/send.ftl
fixes #593 
also supersedes #625 so:
fixes #621 
fixes #622
> display the 'add password' button only when the input field isn't empty

- app/templates/welcome.js
My changes from #574 require the form to be ordered unusually to [apply a outline with CSS](https://github.com/mozilla/send/blob/bd5cdc52f9f979a6f88d35e983cdbd108cf550f2/assets/main.css#L276) when it has keyboard focus.
The ordering of the from was switched back in [this commit ](https://github.com/mozilla/send/commit/bc24a069da62af39efdb3f283ce1d9129ba0598e#diff-60ead385e7fcc0298db5058140959aa0L21) and the outline on keyboard focus was lost / stopped working.
This PR switches the order of the forms input and label elements back again, so that an outline will be shown when the upload button has keyboard focus.
> Keyboard navigation/visual feedback regression

- assets/main.css
Bug ([#609](https://github.com/mozilla/send/issues/609)): Text in input and button are not aligned on the middle axis
Fix: Add `padding-bottom` on the button elements to push their contents a bit higher
> #609 share interface: align text in input and button

- assets/main.css
Bug: The button to set a password had a different look than other buttons on the site
Fix: add `-webkit-appearance: none` on the input element to force browser to discard the default styling. For a reduced test case demonstrating the fix see https://codepen.io/ovl/full/qVYgoO/
> #634: overwrite appearance of password submit input

- assets/main.css
- removed mouse events from child element when dragging is happening.
> stop drag target from flickering when dragging over children

- docker-compose.yml
This fixes https://github.com/mozilla/send/issues/666 by not assuming production in the docker-compose.yml.
**Important Note:** before deploying this, please make sure the production infrastructure actually sets the NODE_ENV variable as this could pose a production => development node env regression if not.
> Make develop the default NODE_ENV

- app/templates/share.js
This resolves #671 
- Calculate hours from the global variable `EXPIRE_SECONDS`
- Use the calculated value to specify the file ttl on the share page
> Use EXPIRE_SECONDS to calculate file ttl for static content

- assets/main.css
The font as marked out by @johngruen in #676 was different (Fira sans) and it has now been set to **Sans sherif** as required.
> changed font to sans sherif: Solves #676

- app/templates/share.js
- app/templates/uploadPassword.js
- assets/main.css
As suggested by @dannycoates #673 all the requested changes have been made. Here's a preview
(its a gif file, please be patient while it loads)
Also Fixes #670 
Please review
> Hide password while Typing and after Entering: Fixes #670 

- app/templates/share.js
fixes: #217 
As requested by @pdehaan and @SoftVision-CiprianMuresan , I have changed the background color of delete btn to red and attached a popup message . Although I believe the hovering effects are not that great. If you suggest me then I'll change it accordingly  
@dannycoates If you don't mind could you review my PR
**Below is a Preview Video**
> delete btn popup attached

- .gitignore
- app/templates/welcome.js
As mentioned by @SoftVision-CosminMuntean and @johngruen at #578, this PR resolves issues related to file uploads of sizes > 2GB. It displays the warning message, cancels the upload and further redirects back to the home page. 
The following preview has been generated for file sizes > 200MB as my laptop crashes for any file having size > 1 GB. However, this limit can be very easily altered as per our needs.
Here is the preview (its a gif file so please be patient while it loads)
@dannycoates @SoftVision-CosminMuntean @johngruen Please review and suggest changes.
> Show Warning, Cancel and Redirect on size > 2GB ; fixes #578

- server/routes/exists.js
- server/routes/metadata.js
> API changes to accommodate 3rd party clients

- assets/main.css
As suggested by @SoftVision-CiprianMuresan at #699, the popup for mobile view has been centered and thus now falls in the visible window. Here's a preview
Please review
> improved popup for mobile display; Fixes #699

- app/routes/index.js
fixes : #663 
Here is a GIF of the changes
> Restricted the banner from showing on unsupported browsers

- app/fileManager.js
- app/templates/file.js
- app/templates/fileList.js
- assets/main.css
- public/locales/en-US/send.ftl
The original PR was filed at #681.
However due to some poor rebasing and squashing habits, the final set of commits messed up a bit. 
All the fine details and conversations can be followed at #681. This PR can be referred for what was done in the files.
And I am a 100% sure that this only contains the intended changes.
And thus, this would be the final PR.
@dannycoates please review this .
If correct, please close #681 
:smile:
> show download Limits on page; Fixes #661

- package-lock.json
- package.json
Please update the `fluent` dependency to 0.4.3.  It has important fixes to the FTL parser.
While the main development of `fluent` continues with the recent 0.6.x versions, I also published 0.4.3 which is API-compatible with other 0.4.x versions. The upgrade should be painless.
`fluent` 0.4.3 supports the recent changes to the Fluent Syntax. It also supports the syntax Send and Pontoon use right now. We expect Pontoon to upgrade their Fluent dependencies early next week, at which point all translations saved back to GitHub will be serialized using the new syntax. This PR will minimize the risk of regressions from that update (which is already low because the changes to the syntax are small).
Some of the syntax changes will require an update to the en-US reference file in this repo, too. …
> Update to fluent 0.4.3

- app/utils.js
Send should not translate URL-safe characters to their non-safe variant when decoding a base64 string, as [`base64-js`](https://github.com/beatgammit/base64-js) is already doing that for us. The library seems to be doing it in a more performant manner, therefore I removed the manual translation from Send in this PR.
See the following snippet in the `base64-js` library:
https://github.com/beatgammit/base64-js/blob/master/index.js#L17-L20
> Don't translate URL-safe chars, b64 is doing it for us

- app/templates/file/index.js
Added a tabindex to the "Copy URL" and "Delete" icon. This will make thoses icons focusable with Tab.
Fix issue #756
> fix: added a tabindex to the CopyUrl and Delete icon

- app/templates/footer/index.js
This PR was submitted to solve the issue presented by @pdehaan in issue #845. This issue revolves around the removal of the `role="presentation"` attribute from `<a>` tags, since it was showing up as an error in sonarwhal linter.
> Remove bad role attribute

- build/fluent_loader.js
- package-lock.json
- package.json
The `_messages` property of `FluentBundle` is considered internal and I'd like to suggest to move Send away from using it. I don't want to make any guarantees that this internal API won't change in a minor release of `fluent`. `FluentResource` is a new public API which can be used to parse, cache and serialize FTL files.
Fixes #611.
> Use FluentResource to parse and serialize FTL files server-side

- app/ui/account.js
- app/ui/archiveTile.js
- app/ui/copyDialog.js
- app/ui/intro.js
- app/ui/modal.js
- app/ui/okDialog.js
- app/ui/promo.js
- app/ui/signupDialog.js
- test/integration/download-tests.js
I'd like to try keeping our use of `class` for style only with no semantic meaning implied, but we need a nice way to select ui elements in tests/etc. I propose using custom elements (using `send-` as the prefix). See how I've modified  `download-tests.js` to use the element as an example.
I probably didn't rename everything that we want to classify, so we can change them as we go. I'd prefer not to make *everything* a custom element so if the selector to get to a specific element within a custom element isn't too complicated I'd prefer that over making new elements. For example the `'send-archive > div'` selector in the download test.
@fzzzy @jrbenny35 thoughts?
> use custom elements instead of adding css classes for selectors

- android/app/src/main/java/org/mozilla/sendandroid/MainActivity.kt
Java has nulls, and any object reference in Java can be null, but in Kotlin parameters default to not null unless the type is specified as `Type?`; our override of onActivityResult was specifying the type of the intent parameter as `Intent` instead of `Intent?`, causing an exception before our code was called. Figuring out how to turn on "break on all exceptions" in Android Studio (which is non-trivial for some reason) finally showed me the stack trace.
> Fixes #1037: Fix back button crasher

- app/ece.js
I figured the current implementation of `encryptedSize` was wrong for Send v2, this PR fixes the it.
Used available constants instead of hard coded numbers where possible.
Explanation:
- `16` was used as overhead per chunk, should be `17` as it also includes a padding delimiter. Simplified to `chunk_meta` constant.
- `floor` was used to determine chunk count, must be `ceil` to include last partially filled chunk (which also includes a tag and delimiter).
Note: the CircleCI `test` stage failed, but this does not seem to be caused by this PR.
> Fix function to calculate encrypted ECE ciphertext length

- public/locales/en-US/send.ftl
Strings shared between prod and vnext are added as comment lines so that once prod strings are no longer needed we can delete all lines above and uncomment shared. vnext only strings are appended to the bottom.
> added vnext strings for translation

- server/readme.md
The links on readme.md were pointing to no longer existent files. With this PR these links are updated to the new location of the files inside the ./bin directory.
> Fix link to dev.js and prod.js files.

- docs/faq.md
in FAQ.md,
The file size limit was previously marked as 2GB (As of April 2018), but now it supports 2.5GB (1GB for non signed in users)
So I have made an attempt to change this to be according to the current file size limits.
I did not create an issue first as I am hoping this fix is trivial and doesn't require an issue first.
> Updated file size limit (as of March 2019)

- android/app/build.gradle
- android/app/src/main/java/org/mozilla/firefoxsend/MainActivity.kt
- android/app/src/main/res/layout/activity_main.xml
- android/build.gradle
Cleaned up a few files related to the Android project to follow common Android/Kotlin conventions.
> Cleanup Android project (Minor refactorings, etc.)

- server/routes/download.js
- server/storage/index.js
This very small change leverages the _hincrby_ function of Redis instead of setting the download count manually. Even though it would be very rare, it could lead to a race condition where multiple requests will set the same download count which causes it be counted as just 1 download.
> Prevent possible download counter race condition

- server/storage/redis.js
Removed deprecated connect_timeout.
Added a new retry_strategy. Retries every 500ms and emits and error to be caught at the 10 seconds limit.
`client.emit` was added since there is a handler for error on storage/index.js. Since returning the error does not throw it (NodeRedis/node_redis#1113)
> Defined retry_strategy for redis. Closes #1292

- build/version_plugin.js
**Problem**: `npm run build` requires a `.git` directory with at least one commit to succeed. The build attempts to read the latest commit hash and write it to `version.json`, for use in the `__version__` route.
**Proposed solution**: If `.git` is missing or empty during npm build, log the error but allow the build to continue. `version.json` is still generated with the same format, but the value of `commit` is `unknown`.
**Rationale**:  Depending on the build process, `.git` may not be preserved in the source code for a variety of reasons. For example putting `.git` in `.dockerignore` is common to cut down on the number of files copied. The fetched git hash is not necessary for normal operation of the app, and only used for [debug/diagnostic …
> Allow successful npm build without .git

- README.md
Just passing by I noticed that it seems like it was overlooked to update the README in https://github.com/mozilla/send/commit/89469e3c9cae3d1f28a8bcac54870ce55af3c34c
> Mention updated Node version 12.x in README

- server/config.js
- server/routes/index.js
Handle Content-Security-Policy headers  for a self hosting FxA stack .
Related Issue : https://github.com/jackyzy823/fxa-selfhosting/issues/1#issuecomment-640233320
> Handle Content-Security-Policy for self hosting FxA

- docs/docker.md
- server/routes/index.js
When serving Firefox Send from a domain of our own, uploads were failing on the following browsers:
- iOS Firefox
- iOS Chrome
- iOS Safari
- Mac Safari
This resolves the issue by generating a proper wss URL for the connect-src CSP directive. Since the default value of `base_url` in the config is `https://send.firefox.com`, the directive will be identical to its value before this change if the `BASE_URL` environment variable is not set
> modify connect-src of Content Security Policy to include dynamic wss URL based on configured base URL
